### ISSUE TITLE
Multiple network cards

### ISSUE THREAD

**Issue by Horcrux7** [onovotny/Zeroconf#57] opened 2016-07-18 16:51 UTC
Please add support for multiple network interfaces. If there are two or more network adapters then the network card which receive the broadcast seems to be randomly. The cause is that subnet mask does not match the broadcast interface.

You can test it if you add a "Microsoft KM-TEST Loopback Adapter" (Win 10) or "Microsoft Loopback Adapter" (older Win). On my system ever the loopback adpater receive the broadcast.

In our Java implementation we iterate over all network interfaces, filter the adapter with one or more IP addresses and send a broadcast to the adapter to the Ip4/Ip6 broadcast address depending of the type of the address. I expect this should also work in the .NET world.

**Comment by onovotny** [comment] 2016-07-18 17:13
Hi,

Are you using the Desktop or UWP version?

The library should aleady use all network interfaces 
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.DotNetCore/NetworkInterface.cs#L29

It gets all of them and then filters out ones that won't support multicast:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.DotNetCore/NetworkInterface.cs#L54-L75

**Comment by Horcrux7** [comment] 2016-07-18 18:52
The UWP version on a desktop from NuGet. Wireshark show that the packets are only send on my loopback adapter. Is this a problem of UWP?

**Comment by onovotny** [comment] 2016-07-18 18:55
Not sure, but the UWP test app works for me and detects items on my LAN ...

The code is here:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.RT/NetworkInterface.cs#L91-L115

**Comment by Horcrux7** [comment] 2016-07-18 19:16
I can not see a loop over multiple adapters in this code. I see only a loop over retries. I see also only a bind to a port and the multicast group. I can not see bind/select to an network adapter. This look like my first Java code which has the same problem.

I am missing a call like bindServiceNameAsync(localServiceName, adapter) https://msdn.microsoft.com/en-us/library/windows/apps/dn279145
But I am not familiar with the .NET API.

**Comment by onovotny** [comment] 2016-07-18 20:04
I am using the other overload, https://msdn.microsoft.com/en-us/library/windows/apps/hh701211.aspx, that is documented as follows

>The BindServiceNameAsync method binds to the local IP addresses of all network interfaces on the local computer on the local service name or UDP port specified in the localServiceName parameter. If the localServiceName parameter is an empty string, the system will select the local UDP port on which to bind.

**Comment by Horcrux7** [comment] 2016-07-18 20:26
This work not with multicast. This work with normal datagram socket where the network stack can detect the right adapter with the target address. I think if no adapter is set then the network stack search for the first matching adapter based on subnet mask or routing table. But multicast address match to all adapters.

Self if this work on your system then you can verify this with wireshark or any other network monitor. You will see that the packets are send only on one adapter. You need to select the adapter before you start the monitoring. 
If the service that you want connect is on a different adapter then this will fail. Most computers has two adapters today. An LAN and a WLAN adapter.  A installed VMWare or Docker produce also extra adapters. It is not an exotic requirements.

I understand your confusing. On my own Java implementation it has me cost many time to understand why it work only on a part of systems.

**Comment by BioSehnsucht** [comment] 2016-09-22 04:40
I may be experiencing the same problem. I have two virtual network adapters from VMware, one from OpenVPN, and then my real one. In my case even trying to capture on all interfaces in Wireshark doesn't reveal anything though... 

Even running the included Zeroconf UWP test program doesn't work - nothing (apparently) happens when I click the buttons?

I basically copied the example find printers code and when I foreach over the results, there are zero results.

```
            IReadOnlyList<IZeroconfHost> results = await ZeroconfResolver.ResolveAsync("_http._tcp.local.");

            foreach (var result in results)
            {
            }
```

**Comment by queequac** [comment] 2016-09-30 10:22
@Horcrux7 I have tested this on my local machine. I started wireshark, monitored my Surface's WLAN adapter and I saw MDNS queries for my test ResolveAsync calls.
I re-started monitoring for the for vEthernet adapter and once again I could see MDNS queries for the test ResolveyAsync calls. (Aside from these queries that adapter did not monitor much else, so it's not just a local loop or something)

So, seems to work as expected here and I cannot verify that this would not work for multicast. (There is also no hint in MSDN that would say this is not working for multicast!)

**Comment by queequac** [comment] 2016-09-30 11:02
@BioSehnsucht @Horcrux7 This might be caused by your network settings. The Test application has capabilities for "Private Networks (Client & Server)" as well as "Internet (Client)".

For public networks you need "Internet (Client & Server)", otherwise there won't be any outbound traffic. Could you check whether adding this capability might help in your case?

**Comment by BioSehnsucht** [comment] 2016-10-01 04:09
Looks like the problem for me was a lack of "Internet (Client & Server)" - I had "Internet (Client)" and "Private Networks (Client & Server)" already selected. I didn't even need Wireshark to confirm it was working this time, since I got results :)

I don't remember enabling "Internet (Client)" (might have turned it on while turning on the private networks one) but I do remember enabling "Private Networks (Client & Server)" because when I made the call to ZeroConf's ResolveAsync I got an actual error logged in Visual Studio stating that I would need that capability.

**Comment by queequac** [comment] 2016-10-01 19:46
@BioSehnsucht I'd guess it was not just a fluke... but who really knows. 😃  Nevertheless, depending on your system settings you might get asked whether a network is public, for work or private when you connect for the first time. Maybe your system treats your current connection simply as private now and that's why it works even with the test app out of the box. 

@onovotny To be on the safe side it might be a good idea adding the "Internet (Client & Server)" capability to the uwp test app. 😄

**Comment by Horcrux7** [comment] 2016-10-04 06:46
@queequac Yes, "Private Networks (Client & Server)" was the trick for me. The other rights I had already. This should be documented because no error occurred this can be a frequently error.

**Comment by queequac** [comment] 2017-02-06 13:56
@onovotny Adding a note to readme.md should be sufficent. Aside from that you could already have closed this issue, no more pain points to be solved. :)

**Comment by onovotny** [comment] 2017-02-06 16:03
Ok, thanks -- I'll add the notes to the UWP section and then close this issue. Thanks all!

**Comment by onovotny** [comment] 2017-02-06 16:13
The readme is updated now to reflect the UWP permissions.

**Closed by onovotny** 2017-02-06 16:13 UTC
